'use client';

import TextSummarizer from '../components/TextSummarizer';

export default function SummarizerPage() {
  return (
    <div style={{ background: '#F8F7F4', minHeight: '100vh', padding: '120px 48px' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <div className="section-label" style={{ marginBottom: 16 }}>AI Demo</div>
        <h1 className="syne" style={{ fontSize: 'clamp(36px,5vw,56px)', fontWeight: 800, color: '#1B2A4A', marginBottom: 24, letterSpacing: '-0.02em' }}>
          Text Summarizer
        </h1>
        <p className="manrope" style={{ fontSize: 18, color: '#6B7280', lineHeight: 1.8, maxWidth: 700, marginBottom: 40 }}>
          Experience AI-powered text summarization. Paste any text below and get a concise summary generated by OpenAI's GPT model.
        </p>
        <TextSummarizer />
      </div>
    </div>
  );
}